### ISSUE TITLE
v1.09 Issues

### ISSUE THREAD

**Issue by Danp2** [loganch/AutoIt-VSCode#134]
Seeing a few issues with the latest release --

- Error in extension host log output 

```
2022-12-01 19:57:25.158 [error] [Damien.autoit] provider FAILED
2022-12-01 19:57:25.163 [error] SyntaxError: Invalid regular expression: /#Region\s(?<regionName>\;**** Directives created by AutoIt3Wrapper_GUI ****).*?#EndRegion/: Nothing to repeat
	at new RegExp (<anonymous>)
	at c:\Users\danpo\.vscode\extensions\damien.autoit-1.0.9\dist\extension.js:1:2932754
	at c (c:\Users\danpo\.vscode\extensions\damien.autoit-1.0.9\dist\extension.js:1:2932992)
	at Object.provideDocumentSymbols (c:\Users\danpo\.vscode\extensions\damien.autoit-1.0.9\dist\extension.js:1:2933051)
	at s.provideDocumentSymbols (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:37637)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:68251
	at ne._withAdapter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:67325)
	at ne.$provideDocumentSymbols (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:68229)
	at l._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:13680)
	at l._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:13362)
	at l._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:12081)
	at l._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:10834)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:8941
	at h.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
	at v.deliver (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
	at g.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
	at r.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:70:16515)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:118:17104
	at h.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
	at v.deliver (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
	at g.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
	at r.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:70:16515)
	at o._receiveMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:70:21327)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:70:18770
	at h.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
	at v.deliver (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
	at g.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
	at g.acceptChunk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:70:13346)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:70:12476
	at Socket.i (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:70:24594)
	at Socket.emit (node:events:526:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```
- Errors related to smarthelp where full path isn't provided for .au3 file (these files are located in one of the `autoit.includePaths` paths).

Example setup config --

```json
       "autoit.smartHelp": {
			"_AD_": {
				"chmPath": "C:\\Users\\danpo\\AppData\\Autoit.Advanced.Help\\AD.chm",
				"udfPath": [
					"AD.au3"
				]
			},
			"_OL_": {
				"chmPath": "C:\\Users\\danpo\\AppData\\Autoit.Advanced.Help\\OutlookEX.chm",
				"udfPath": [
					"OutlookEX.au3",
					"OutlookEX_Base.au3"
				]
			},
			"_TS_": {
				"chmPath": "C:\\Users\\danpo\\AppData\\Autoit.Advanced.Help\\TaskScheduler.chm",
				"udfPath": [
					"TaskScheduler.au3"
				]
			},
			"_WD_": {
				"chmPath": "C:\\Users\\danpo\\AppData\\Autoit.Advanced.Help\\Webdriver.chm",
				"udfPath": [
					"C:\\Users\\danpo\\OneDrive\\Documents\\GitHub\\WebDriver\\wd_core.au3",
					"C:\\Users\\danpo\\OneDrive\\Documents\\GitHub\\WebDriver\\wd_helper.au3",
					"C:\\Users\\danpo\\OneDrive\\Documents\\GitHub\\WebDriver\\wd_cdp.au3"
				]
			}
		}
```

Notification show in VS GUI --
`File "C:\Program Files (x86)\AutoIt3\Advanced.Help\HelpFiles\OutlookEX.au3" not found (autoit.smartHelp._OL_.udfPath[0])`

**Comment by loganch** [comment]
Yep, on the first error it looks like a Region with asterisks, and backslashes like the auto-generated directives regions and the regions generated by Koda. I've just about got a fix working for that.
