### ISSUE TITLE
Error in Extension Host Log when trying to hover unknown words

### ISSUE THREAD

**Issue by Fedorazzz** [loganch/AutoIt-VSCode#61]
When mouse runs over words without description Exthost send error to Log.
Vscode version: 1.54.3

Here`s the text of error:
```
[2021-03-16 19:35:18.039] [exthost] [error] [Damien.autoit] provider FAILED
[2021-03-16 19:35:18.039] [exthost] [error] Error: Illegal argument, contents must be defined
	at new Z (c:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:81:23473)
	at new Z (c:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:81:11705)
	at Object.provideHover (c:\SCRIPTS\AutoIt-VSCode!\dist\extension.js:6150:12)
	at c:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:156761
	at c:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:7538
	at new Promise (<anonymous>)
	at Object.g [as asPromise] (c:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:7510)
	at n.provideHover (c:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:156732)
	at c:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:179262
	at Se._withAdapter (c:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:176060)
	at Se.$provideHover (c:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:179238)
	at c._doInvokeHandler (c:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:10509)
	at c._invokeHandler (c:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:10201)
	at c._receiveRequest (c:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:8820)
	at c._receiveOneMessage (c:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:7673)
	at c:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:5782
	at g.fire (c:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
	at p.fire (c:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15443)
	at c:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:29119
	at g.fire (c:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
	at p.fire (c:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15443)
	at t._receiveMessage (c:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:20693)
	at c:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17587
	at g.fire (c:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
	at l.acceptChunk (c:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12808)
	at c:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12156
	at Socket.E (c:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:12375)
	at Socket.emit (events.js:315:20)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:271:9)
	at Socket.push (_stream_readable.js:212:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
	at Pipe.callbackTrampoline (internal/async_hooks.js:120:14)
```

**Comment by loganch** [comment]
Hmmm, looks like I mixed up the fact that _undefined_ is okay to return from _HoverProvider_, but not as the content inside of a _Hover_...
